src/views/repository/EvaluateAutomaticNew.vue
src/views/repository/EvaluateManual.vue

Refatoração da home de Testes, de acordo com o design review.
Componentes alterados:
EvaluateAutomaticNew;
EvaluateManual.

[Refactor] Tests redesign home

---

src/components/repository/home/HomeRepositoryCard.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* Added knowledge bases count in repository card

feat: added knowledge bases count in repository card

---

src/components/shared/HighlightedCode.vue
src/views/repository/Integration.vue

Alterações de design review na tela de API nas Inteligências Artificiais de Classificação.
Componentes alterados:
HighlightedCode;
Integration.

[Feature] Design review Api page

---

src/components/ModalDependingOnFlowsLength.vue
src/components/repository/sidebar/SideBar.vue
src/components/translate/NewTranslationsStatus.vue
src/components/translate/TranslateExampleTable.vue
src/components/translate/TranslateList.vue
src/components/translate/TranslatedExampleTable.vue
src/locales/pt_br.json
src/views/repository/Translate.vue
src/views/repository/TranslateExternal.vue
src/views/repository/Translations.vue

Redesign da tela de status de tradução nas Inteligências Artificiais de Classificação.
Componentes alterados:
Translations.

[Feature] Translation status redesign

---

src/views/repository/Settings.vue
src/views/repository/loadings/Settings.vue

A tela de Ajustes agora terá uma página de carregamento de acordo com o Skeleton Loading do unnnic.

[Feature] Settings skeleton loading

---

src/components/translate/NewTranslationsStatus.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

Ajustes na tela de Status da tradução conforme solicitado no design review.

[Feature] Design review translation status

---

src/components/repository/EditRepositoryForm.vue
src/components/repository/RepositoryVersionList.vue
src/components/repository/repository-log/RepositoryLogList.vue
src/components/shared/IntentPagination.vue
src/views/repository/Versions.vue
src/views/repository/loadings/IntegrationGenerator.vue
src/views/repository/loadings/IntegrationRequest.vue
src/views/repository/loadings/IntentData.vue
src/views/repository/loadings/SettingsModal.vue
src/views/repository/loadings/SettingsTab.vue
src/views/repository/loadings/SettingsVersions.vue

Algumas telas de carregamento não estavam de acordo com o Skeleton Loading do unnnic. Tais como:
- Ajustes;
- Api;
- Interações.

[Feature] Skeleton loading adjustments

---

config.js.tmpl
public/config.js
src/App.vue
src/api/nexusaiAPI.js
src/components/repository/CreateRepository/CreateRepositoryForm.vue
src/components/repository/CreateRepository/DefinitionsTab.vue
src/components/repository/home/HomeRepositoryCard.vue
src/components/repository/home/IntelligenceFromProjectItem.vue
src/components/repository/home/SideBarContentBases.vue
src/components/repository/home/SideBarQuickTest.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/router/index.js
src/store/auth/state.js
src/store/index.js
src/utils/RemoveBulmaMixin.js
src/views/Home.vue
src/views/repository/content/Bases.vue
src/views/repository/content/BasesForm.vue
src/views/repository/content/BasesFormFiles.vue
src/views/repository/content/BasesFormFilesItem.vue
src/views/repository/content/ContentAdjustments.vue
src/views/repository/content/Navigation.vue
src/views/repository/content/Tests.vue

All the integrations for WeniGPT:
* CRUD of intelligences;
* CRUD of intelligences bases;
* CRUD of intelligences bases texts;
* CRUD of intelligences bases files;
* Quick test chat.

Nexus 509 crud integrations of intelligences weni gpt

---

src/api/nexusaiAPI.js
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/BasesForm.vue
src/views/repository/content/BasesFormFilesItem.vue
src/views/repository/content/BasesFormSites.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Integrations for content base sites.
Adds integrations for content base sites: list, create and delete.

[NEXUS-787] Content bases sites integrations

---

src/components/InputWithHightlights.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
For somehow, tag p was causing lint bug claiming that the tag could have been closed previously, but wasn't.
Changed tag p to section.

fix(lint-bug): changes tag p to section to remove lint bug closing tag

---

src/api/nexusaiAPI.js
src/views/repository/content/BasesForm.vue
src/views/repository/content/BasesFormSites.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Needs to insert manually load_type attribute when adding a new file to content base.
* Adds fixed attribute load_type;
* Fixes remotion of a site locally when user delete it.

[NEXUS-915] Fixed load type attribute in file adition in content base

---

src/components/ModalNext.vue
src/components/actions/ModalActions.vue
src/components/actions/ModalChangeAction.vue
src/components/actions/ModalRemoveAction.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
modal for CRUD on the actions screen
- add modal
- edit modal 
- remove modal
- [FIGMA Router](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?type=design&node-id=207%3A4101&mode=design&t=2tR3pqYxHPV5do5p-1)

[Nexus 913] modal add router actions

---

src/components/customization/CustomizationForm.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- [Design](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?type=design&node-id=173%3A2035&mode=dev)

[Nexus-977] customize router tab

---

src/components/PageContainer.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/Home.vue
src/views/repository/content/BasesForm.vue
src/views/repository/content/BasesFormFiles.vue
src/views/repository/content/BasesFormGenericList.vue
src/views/repository/content/BasesFormSites.vue
src/views/repository/content/router/RouterActions.vue
src/views/repository/content/router/RouterTuningsAdvanced.vue

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Final adjustments of Router/Brain feature.
* Text adjustments;
* Back page button;
* Filtering Brain's list of AIs;
* Remove quick test;
* Insert warning in an alert-style bar if Brain is deactivated;
* Change icon;
* WeniGPT adjustments.

[Nexus-1055] Router general adjustments

---

package.json

* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Updates Unnnic version.

Updates Unnnic

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/router/RouterCustomization.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- changes in personality translation logic
- adding error feedback when trying to fetch personalization data from the API

[Nexus-1059] customize screen adjustments

---

src/components/actions/ModalActions.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Adding text-truncate logic

[NEXUS-1060] adjusting logic for flows with large name

---

src/components/actions/ModalActions.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- show message when there is no flow to select
- Bug in the add action modal (a blank appears) when no flow matching the search was found: show message that no matching flow was found

[Nexus-1072] modal adjustments add action

---

src/views/repository/content/router/RouterTuningsAdvanced.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adding cursor pointer in input radio brain

[NEXUS-1091] cursor pointer input radio brain

---

src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Required fields
- Loading data logic

[Nexus-1095] improve tunings configure required fields data loaded

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/BasesForm.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- search bar in content tab

Nexus 1093 search bar in content tab

---

public/config.js

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other

[NEXUS-1130] Change default option

---

src/views/repository/content/router/RouterTunings.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- break build

Fix router tunings break build

---

src/App.vue
src/components/ModalWarn.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/router/RouterTuningsAdvanced.vue

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other

[Nexus-1144] change texts modal brain and alert

---

config.js.tmpl
package.json
src/api/nexusaiAPI.js
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/utils/FlowPreview.js
src/views/repository/content/BasesForm.vue
src/views/repository/content/Tests.vue
yarn.lock

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds Brain Preview.
- [Router - Preview](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?node-id=193%3A1755&mode=dev)

[Nexus-1121] Brain Preview

---

src/views/repository/content/Tests.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Uses real project UUID.

fix(brain-preview): uses real project uuid

---

src/views/repository/content/Tests.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
* Adds quick replies buttons.
- [Router - Quick Replies](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?node-id=858-6401&mode=dev)

[Nexus-1172] Quick Replies

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/BasesForm.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adding dropdown with options
- adding new translations
- [Design](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?type=design&node-id=897%3A5303&mode=dev)

Nexus 1171 refresh simulator

---

src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Other users read token
adding nativeType in UnnicInput

[Nexus-1176] hide token from chat gpt

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/router/index.js
src/views/repository/content/BasesForm.vue
src/views/repository/content/Tests.vue
src/views/repository/content/router/ModalPreviewQRCode.vue
src/views/repository/content/router/RouterPreviewFullPage.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Users who want to test preview on mobile.
* Adds modal with QR Code to open on mobile;
* Adds page to show preview on full page.
- [Router - Preview on mobile](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?node-id=901-5734&mode=dev)

[Nexus-1173] Preview on mobile

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/Tests.vue
src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The user wants to see what changes were applied.
* Adds log on Brain preview.
- [Router - Ajustes 2](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?node-id=916-15010&mode=dev)

[Nexus-1174] Changes Log on Preview

---

src/utils/FlowPreview.js

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other

Fixes quick replies disappearing bug

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/utils/handleLetters.js
src/views/repository/content/Tests.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other

Nexus 1203 adjusts change translation

---

src/views/repository/content/router/RouterTunings.vue
src/views/repository/content/router/RouterTuningsAdvanced.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- changing locale some params in tuning
- [Design](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?type=design&node-id=860%3A7433&mode=dev)

Nexus 1202 tuning passing parameters for advanced and updated design

---

src/components/QuickTest/AnswerSources.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/Tests.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The user wants to see where the answers were generated from.
* Adds AnswerSources component.
- [Router - Ajustes 2](https://www.figma.com/file/QE22CBVh18ORmxe1HhDUkD/Router?node-id=856-1675&mode=dev)

[Nexus-1127] Preview: Sources of Answers

---

src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new option for chatgpt model
- adding gpt-4o on Brain

[NEXUS-1252] adding gpt-4o in RouterTunnings

---

src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/Tests.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
The user wants to know when a flows was started and when it was finished.
* Adds a message when a flows starts and when it finishes.

[Nexus-1248] Flows Status on Preview

---

package.json
yarn.lock

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- update slider component
- update unnnic system

[NEXUS-1223] update unnnic-system

---

src/views/repository/content/Tests.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fixes a bug in #329 when it appeared false flow end status.

[Nexus-1248] Fixes False Flowsend Status

---

src/views/repository/content/router/RouterTunings.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- match figma
- adding label
old:
new:

[NEXUS-1223] add-labels-slider-component-tunings 

---

src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- weni gpt is not prepared for this
- removing select language in weniGpt

CHANGE SELECT LANGUAGE IN ROUTER TUNING

---

src/views/repository/content/BasesForm.vue
src/views/repository/content/BasesFormFiles.vue

* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- fix bug search after upload content
- refactoring logic debounce and fix logic components

[Nexus-1281] FIX SEARCH NEW FILES

---

src/components/QuickTest/AnswerSources.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes duplicated sources.

[Nexus-1267] Brain Preview: Prevents Duplicated Sources

---

src/views/repository/content/Tests.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Removes loading bubble when error occours.

[Nexus-1266] Brain Preview: Removes Loading Bubble When Error Occours

---

src/components/QuickTest/AnswerSources.vue
src/locales/en.json
src/locales/es.json
src/locales/pt_br.json
src/views/repository/content/BasesFormFilesItem.vue
src/views/repository/content/router/RouterCustomization.vue
src/views/repository/content/router/RouterTunings.vue

* * [ ] Bugfix
* * [X] Feature
* * [ ] Tests
* * [ ] Other
- necessary adjustments to improve user experience
- adjustments to the customization placeholder
- personality change for select
- add collapse to font preview
- add tooltype to token in tuning
- change the rendering order in tuning
- adjusting files in content
- [Design](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?m=dev&node-id=1291%3A8099)
- [Design 2](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?m=dev&node-id=1294%3A15451)
- [Design 3](https://www.figma.com/design/QE22CBVh18ORmxe1HhDUkD/Brain?m=dev&node-id=858%3A6401)

[Nexus-1291] - Update design

---

src/views/repository/content/router/RouterTunings.vue

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
When user edits token it was not binded with Brain state values.

[Nexus-1326] Bug: Fixes Token Attribute Bind

---

public/index.html

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Forces reload cache for environment variables.

feat(cache): forces cache reload

---

src/components/form-generator/inputs/ChoiceInput.vue
src/components/inputs/EntitiesInput/EntityForm.vue
src/components/inputs/EntitiesInput/NewEntitiesInput.vue

* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
* Replaces old depreciated `UnnnicAutocomplete` to use `UnnnicSelectSmart` with `autocomplete`.

[Nexus-1536] Replacement of the Remaining Depreciated Components

---

src/__tests__/components/form-generator/inputs/__snapshots__/ChoiceInput.spec.js.snap
src/__tests__/components/shared/Messages.spec.js

* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
-  CI problems
- update snapshot
- adjust expect logic in messages

[NEXUS-1617] IC correction

---

.github/workflows/unit-tests.yaml
README.md
jest.config.js
package.json

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Config Codecov at this repository.
- Added coverage script at package.

[ENGAGE-1240] Codecov

---

nginx.conf
public/index.html

* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
* Fixes Hotjar CSP settings.

[Nexus-1693] Fixes CSP settings

---

src/components/form-generator/FormGenerator.vue
src/components/form-generator/inputs/ChoiceInput.vue

* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
When the advanced settings are default, this section should be hidden.

[Nexus-1734] Hides Advanced Settings When Advanced Settings are Default
